name: "Build"

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

permissions:
  contents: read

jobs:
  DeployOnMacOSArm64:
    runs-on: macos-15

    timeout-minutes: 180

    environment: production

    steps:
      - name: Get access token
        run: |
          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
          if [[ -z "$ACCESS_TOKEN" ]]; then
            echo "Failed to get access token"
            exit 1
          fi
          printf 'VCPKG_BINARY_SOURCES=clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},readwrite,Authorization: Bearer %s\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
          echo "::add-mask::$ACCESS_TOKEN"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet arm64-osx-obs

  DeployOnMacOSX64:
    runs-on: macos-15

    timeout-minutes: 180

    environment: production

    steps:
      - name: Get access token
        run: |
          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
          if [[ -z "$ACCESS_TOKEN" ]]; then
            echo "Failed to get access token"
            exit 1
          fi
          printf 'VCPKG_BINARY_SOURCES=clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},readwrite,Authorization: Bearer %s\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
          echo "::add-mask::$ACCESS_TOKEN"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-osx-obs

  DeployOnWindows:
    runs-on: windows-2022

    timeout-minutes: 180

    environment: production

    steps:
      - name: Get access token
        shell: bash
        run: |
          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
          if [[ -z "$ACCESS_TOKEN" ]]; then
            echo "Failed to get access token"
            exit 1
          fi
          printf 'VCPKG_BINARY_SOURCES=clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},readwrite,Authorization: Bearer %s\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
          echo "::add-mask::$ACCESS_TOKEN"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        shell: pwsh
        run: .\bootstrap-vcpkg.bat

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-windows-static-md-obs --debug

  DeployOnUbuntu:
    runs-on: ubuntu-24.04

    timeout-minutes: 60

    environment: production

    steps:
      - name: Get access token
        run: |
          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
          if [[ -z "$ACCESS_TOKEN" ]]; then
            echo "Failed to get access token"
            exit 1
          fi
          printf 'VCPKG_BINARY_SOURCES=clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},readwrite,Authorization: Bearer %s\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
          echo "::add-mask::$ACCESS_TOKEN"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-linux-obs
