name: "Deploy"

on:
  push:
    branches: [main]
  schedule:
    - cron: "23 9 * * *" # Every day at 09:23 UTC
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  VCPKG_BINARY_SOURCES: clear;http,http://localhost:8080/{name}/{version}/{sha},readwrite

permissions:
  contents: read

jobs:
  DeployOnMacOSArm64:
    runs-on: macos-15

    timeout-minutes: 180

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &
          PID=$!
          echo "Proxy started with PID: $PID"
          echo "CIPROXY_PID=$PID" >> $GITHUB_ENV
          sleep 3

      - name: Set up vcpkg
        run: echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet arm64-osx-obs

      - name: Stop ciproxy
        run: |
          echo "Stopping ciproxy with PID: $CIPROXY_PID"
          kill -TERM "$CIPROXY_PID" || echo "Failed to stop ciproxy"
          wait $CIPROXY_PID || true
          echo "Ciproxy stopped."

      - name: list artifacts
        run: ls -la vcpkg_artifacts

  DeployOnMacOSX64:
    runs-on: macos-15

    timeout-minutes: 180

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &
          PID=$!
          echo "Proxy started with PID: $PID"
          echo "CIPROXY_PID=$PID" >> $GITHUB_ENV
          sleep 3

      - name: Set up vcpkg
        run: echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-osx-obs

      - name: Stop ciproxy
        run: |
          echo "Stopping ciproxy with PID: $CIPROXY_PID"
          kill -TERM "$CIPROXY_PID" || echo "Failed to stop ciproxy"
          wait $CIPROXY_PID || true
          echo "Ciproxy stopped."

      - name: list artifacts
        run: ls -la vcpkg_artifacts

  DeployOnWindows:
    runs-on: windows-2022

    timeout-minutes: 180

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &
          PID=$!
          echo "Proxy started with PID: $PID"
          echo "CIPROXY_PID=$PID" >> $GITHUB_ENV
          sleep 3

      - name: Set up vcpkg
        run: echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-windows-static-md-obs

      - name: Stop ciproxy
        run: |
          echo "Stopping ciproxy with PID: $CIPROXY_PID"
          kill -TERM "$CIPROXY_PID" || echo "Failed to stop ciproxy"
          wait $CIPROXY_PID || true
          echo "Ciproxy stopped."

      - name: list artifacts
        run: ls -la vcpkg_artifacts

  DeployOnUbuntu:
    runs-on: ubuntu-24.04

    timeout-minutes: 60

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &
          PID=$!
          echo "Proxy started with PID: $PID"
          echo "CIPROXY_PID=$PID" >> $GITHUB_ENV
          sleep 3

      - name: Set up vcpkg
        run: echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-linux-obs

      - name: Stop ciproxy
        run: |
          echo "Stopping ciproxy with PID: $CIPROXY_PID"
          kill -TERM "$CIPROXY_PID" || echo "Failed to stop ciproxy"
          wait $CIPROXY_PID || true
          echo "Ciproxy stopped."

      - name: list artifacts
        run: ls -la vcpkg_artifacts
