name: "Deploy"

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  VCPKG_BINARY_SOURCES: clear;http,http://localhost:8080/{name}/{version}/{sha},readwrite
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

permissions:
  contents: read

jobs:
  DeployOnMacOSArm64:
    runs-on: macos-15

    timeout-minutes: 180

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet arm64-osx-obs

  DeployOnMacOSX64:
    runs-on: macos-15

    timeout-minutes: 180

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-osx-obs

  DeployOnWindows:
    runs-on: windows-2022

    timeout-minutes: 180

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        shell: pwsh
        run: .\bootstrap-vcpkg.bat

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-windows-static-md-obs

  DeployOnUbuntu:
    runs-on: ubuntu-24.04

    timeout-minutes: 60

    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Start ciproxy
        working-directory: ${{ github.workspace }}/ciproxy
        run: |
          go build
          MASTER_TOKEN="${{ secrets.MASTER_TOKEN }}" PORT=8080 nohup ./ciproxy &

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Build
        run: $VCPKG_ROOT/vcpkg install --triplet x64-linux-obs
